# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ master ]
  release:
    types: [created, edited]

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build native only with Gradle
      if: ${{ matrix.os != 'ubuntu-latest'}}
      run: gradle build -p nativeOnly
      env:
        VERSION: ${{ github.event.release.tag_name }}

    - name: Build with Gradle
      if: ${{ matrix.os == 'ubuntu-latest'}}
      run: gradle build
      env:
        VERSION: ${{ github.event.release.tag_name }}

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: gradle publish
      env:
        VERSION: ${{ github.event.release.tag_name }}
        USERNAME: ${{ secrets.GITLAB_USERNAME }}
        TOKEN: ${{ secrets.GITLAB_TOKEN }}
