# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Demo web version

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and publish with Gradle
        run: gradle korge:jsBrowserProductionWebpack
      - name: Deploy 🚀 to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: github-pages # The branch the action should deploy to.
          FOLDER: korge/build/distributions # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
